import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
    const password = await bcrypt.hash("root", 10);

    await prisma.employee.upsert({
        where: { username: "manager" },
        update: {
            email: "manager@babasahebkavad.com",
            name: "Bank Manager",
            password,
            role: "MANAGER",
            status: "ACTIVE",
            isLocked: false,
            failedAttempts: 0,
            lockUntil: null,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        create: {
            username: "manager",
            email: "manager@babasahebkavad.com",
            name: "Bank Manager",
            password,
            role: "MANAGER",
            status: "ACTIVE",
            isLocked: false,
            failedAttempts: 0,
        },
    });

    await prisma.employee.upsert({
        where: { username: "employee" },
        update: {
            email: "employee@babasahebkavad.com",
            name: "Bank Employee",
            password,
            role: "EMPLOYEE",
            status: "ACTIVE",
            isLocked: false,
            failedAttempts: 0,
            lockUntil: null,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        create: {
            username: "employee",
            email: "employee@babasahebkavad.com",
            name: "Bank Employee",
            password,
            role: "EMPLOYEE",
            status: "ACTIVE",
            isLocked: false,
            failedAttempts: 0,
        },
    });

    console.log("Manager and Employee logins created:");
    console.log("Username: manager / employee");
    console.log("Password: root");

    const branches = [
      {
        id: "headquarters",
        nameEn: "Head Office",
        nameMr: "मुख्यालय",
        addressEn: "S.T. Stand, Nighoj–Parner Road, Nighoj, Tal. Parner, Dist. Ahmednagar",
        addressMr: "एस. टी. स्टँड, निघोज–पारनेर रोड, निघोज, ता. पारनेर, जि. अहमदनगर",
        cityEn: "Ahmednagar",
        cityMr: "अहमदनगर",
        contact: "(02488) 230449, 230442",
        managerNameEn: "Branch Manager",
        managerNameMr: "शाखा व्यवस्थापक",
        googleMapUrl: "https://maps.google.com/?q=Nighoj+Parner+Ahmednagar",
      },
      {
        id: "alkuti",
        nameEn: "Alkuti",
        nameMr: "अळकुटी",
        addressEn: "Near S. T. Stand, Alkuti, Tal. Parner, Dist. Ahmednagar",
        addressMr: "एस. टी. स्टँड जवळ, अळकुटी, ता. पारनेर, जि. अहमदनगर",
        cityEn: "Ahmednagar",
        cityMr: "अहमदनगर",
        contact: "(02488) 250092",
        managerNameEn: "Branch Manager",
        managerNameMr: "शाखा व्यवस्थापक",
        googleMapUrl: "https://maps.google.com/?q=Alkuti+Parner",
      },
      {
        id: "supa",
        nameEn: "Supa",
        nameMr: "सुपा",
        addressEn: "Parner-Nagar Road, Near Omkar Hospital, Supa, Tal. Parner, Dist. Ahmednagar",
        addressMr: "पारनेर-नगर रोड, ओंकार हॉस्पिटल जवळ, सुपा, ता. पारनेर, जि. अहमदनगर",
        cityEn: "Ahmednagar",
        cityMr: "अहमदनगर",
        contact: "(02488) 293092",
        managerNameEn: "Branch Manager",
        managerNameMr: "शाखा व्यवस्थापक",
        googleMapUrl: "https://maps.google.com/?q=Supa+Parner",
      },
      {
        id: "shirur",
        nameEn: "Shirur",
        nameMr: "शिरूर",
        addressEn: "Market Committee Road, behind Mahanagar Bank, Tal. Parner, Dist. Ahmednagar",
        addressMr: "मार्केट कमिटी रोड, महानगर बँकेच्या पाठीमागे, पारनेर, जि. अहमदनगर",
        cityEn: "Ahmednagar",
        cityMr: "अहमदनगर",
        contact: "(02488) 222464",
        managerNameEn: "Branch Manager",
        managerNameMr: "शाखा व्यवस्थापक",
        googleMapUrl: "https://maps.google.com/?q=Shirur+Parner",
      },
      {
        id: "shirur-addl",
        nameEn: "Shirur (Additional)",
        nameMr: "शिरूर (अतिरिक्त)",
        addressEn: "Nagar-Pune Road, Wadgaon Rasai, Tal. Parner, Dist. Ahmednagar",
        addressMr: "नगर-पुणे रोड, वाडगाव रासाई, ता. पारनेर, जि. अहमदनगर",
        cityEn: "Ahmednagar",
        cityMr: "अहमदनगर",
        contact: "9881717236",
        managerNameEn: "Branch Manager",
        managerNameMr: "शाखा व्यवस्थापक",
        googleMapUrl: "https://maps.google.com/?q=Wadgaon+Rasai",
      },
      {
        id: "jawala",
        nameEn: "Jawala",
        nameMr: "जवळा",
        addressEn: "Near S. T. Stand, Tal. Parner, Dist. Ahmednagar",
        addressMr: "एस. टी. स्टँड जवळ, ता. पारनेर, जि. अहमदनगर",
        cityEn: "Ahmednagar",
        cityMr: "अहमदनगर",
        contact: "(02488) 214091",
        managerNameEn: "Branch Manager",
        managerNameMr: "शाखा व्यवस्थापक",
        googleMapUrl: "https://maps.google.com/?q=Jawala+Parner",
      },
      {
        id: "maltan",
        nameEn: "Maltan",
        nameMr: "मळतण",
        addressEn: "Near Bank of Maharashtra, S. T. Stand, Maltan, Tal. Shirur, Dist. Pune",
        addressMr: "बँक ऑफ महाराष्ट्र शेजारी, एस. टी. स्टँड जवळ, मळतण, ता. शिरूर, जि. पुणे",
        cityEn: "Pune",
        cityMr: "पुणे",
        contact: "(02137) 251799, 9193834775",
        managerNameEn: "Branch Manager",
        managerNameMr: "शाखा व्यवस्थापक",
        googleMapUrl: "https://maps.google.com/?q=Maltan+Shirur",
      },
      {
        id: "taklihaji",
        nameEn: "Taklihaji",
        nameMr: "टाकळीहाजी",
        addressEn: "Near S. T. Stand, Taklihaji, Tal. Shirur, Dist. Pune",
        addressMr: "एस. टी. स्टँड जवळ, टाकळीहाजी, ता. शिरूर, जि. पुणे",
        cityEn: "Pune",
        cityMr: "पुणे",
        contact: "9860398684",
        managerNameEn: "Branch Manager",
        managerNameMr: "शाखा व्यवस्थापक",
        googleMapUrl: "https://maps.google.com/?q=Taklihaji+Shirur",
      },
      {
        id: "koregaon-bhima",
        nameEn: "Koregaon Bhima",
        nameMr: "कोरेगाव भिमा",
        addressEn: "Zonish Commercial Complex, S. No. 52, Near HDFC Bank, Shirur-Pune Rd, Pune",
        addressMr: "झोनिश कमर्शियल कॉम्प्लेक्स, सर्वे नं. ५२, एच.इ.एफ.सी.बँक जवळ, शिरूर-पुणे रोड, कोरेगाव भिमा, ता. शिरूर, जि. पुणे",
        cityEn: "Pune",
        cityMr: "पुणे",
        contact: "9284961105",
        managerNameEn: "Branch Manager",
        managerNameMr: "शाखा व्यवस्थापक",
        googleMapUrl: "https://maps.google.com/?q=Koregaon+Bhima",
      },
      {
        id: "wagholi",
        nameEn: "Wagholi",
        nameMr: "वाघोली",
        addressEn: "Mangalmurti Complex, S. No. 648/1, Shop 8 & 10, Ahmednagar-Pune Rd, Haveli, Pune",
        addressMr: "मंगलमूर्ती कॉम्प्लेक्स, सर्वे नं. ६४८/१, गाळा नं. ८ व १० अहमदनगर-पुणे रोड, वाघोली, ता. हवेली, जि. पुणे",
        cityEn: "Pune",
        cityMr: "पुणे",
        contact: "020-29919338, 9604844029",
        managerNameEn: "Branch Manager",
        managerNameMr: "शाखा व्यवस्थापक",
        googleMapUrl: "https://maps.google.com/?q=Wagholi+Pune",
      },
      {
        id: "alephata",
        nameEn: "Alephata",
        nameMr: "आळेफाटा",
        addressEn: "Near Sangamner Merchant Co-op Bank, Nagar-Kalyan Rd, Junnar, Pune",
        addressMr: "संगमनेर मर्चंट को-ऑप बँक जवळ, नगर-कल्याण रोड, आळेफाटा, ता. जुन्नर, जि. पुणे",
        cityEn: "Pune",
        cityMr: "पुणे",
        contact: "(02132) 263441",
        managerNameEn: "Branch Manager",
        managerNameMr: "शाखा व्यवस्थापक",
        googleMapUrl: "https://maps.google.com/?q=Alephata+Junnar",
      },
      {
        id: "lonimawala",
        nameEn: "Lonimawala",
        nameMr: "लोणीमावळा",
        addressEn: "Lonimawala, Tal. Parner, Dist. Ahmednagar",
        addressMr: "लोणीमावळा, ता. पारनेर, जि. अहमदनगर",
        cityEn: "Ahmednagar",
        cityMr: "अहमदनगर",
        contact: "9604393234",
        managerNameEn: "Branch Manager",
        managerNameMr: "शाखा व्यवस्थापक",
        googleMapUrl: "https://maps.google.com/?q=Lonimawala+Parner",
      },
      {
        id: "chandannagar",
        nameEn: "Chandannagar",
        nameMr: "चंदननगर",
        addressEn: "Chandan Complex, Shivaji Chowk, Chandannagar, Pune",
        addressMr: "चंदन कॉम्प्लेक्स, शिवाजी चौक, चंदननगर, पुणे",
        cityEn: "Pune",
        cityMr: "पुणे",
        contact: "(020) 64058266, 9421059989",
        managerNameEn: "Branch Manager",
        managerNameMr: "शाखा व्यवस्थापक",
        googleMapUrl: "https://maps.google.com/?q=Chandannagar+Pune",
      }
    ];

    const defaultGalleryItems = [
      {
        id: "gallery-1",
        titleEn: "Annual General Body Meeting 2024-25",
        titleMr: "वार्षिक सर्वसाधारण सभा २०२४-२५",
        category: "agm",
        imageUrl: "/images/image-3.png",
        descriptionEn: "Members and Directors aligning on society financial growth guidelines during the AGM in Pune.",
        descriptionMr: "पुण्यात आयोजित वार्षिक सर्वसाधारण सभेमध्ये सदस्य व संचालकांनी संस्थेच्या आर्थिक विकासावर चर्चा केली.",
        sortOrder: 1,
        isActive: true,
      },
      {
        id: "gallery-2",
        titleEn: "Community Blood Donation Camp",
        titleMr: "रक्तदान शिबिर",
        category: "social",
        imageUrl: "/images/gallery_donation.png",
        descriptionEn: "Volunteers and medical staff organizing a blood drive on the founder's birth anniversary.",
        descriptionMr: "संस्थापकांच्या जयंतीनिमित्त स्वयंसेवक आणि वैद्यकीय कर्मचाऱ्यांनी रक्तदान शिबिराचे आयोजन केले.",
        sortOrder: 2,
        isActive: true,
      },
      {
        id: "gallery-3",
        titleEn: "Village Afforestation Tree Plantation",
        titleMr: "वृक्षारोपण अभियान",
        category: "social",
        imageUrl: "/images/gallery_plantation.png",
        descriptionEn: "Co-operative youth volunteers planting over 1,000 tree saplings in Nighoj village surroundings.",
        descriptionMr: "सहकारी तरुण स्वयंसेवकांनी निघोज गावच्या परिसरात १,००० हून अधिक झाडांची रोपे लावली.",
        sortOrder: 3,
        isActive: true,
      },
      {
        id: "gallery-4",
        titleEn: "Inauguration of Thane West Branch",
        titleMr: "ठाणे पश्चिम शाखा उद्घाटन",
        category: "inauguration",
        imageUrl: "/images/image8.jpeg",
        descriptionEn: "Opening of our 12th branch at Thane West to serve metropolitan merchant portfolios.",
        descriptionMr: "महानगरीय व्यापारी सेवांसाठी ठाणे पश्चिम येथे आमच्या १२ व्या शाखेचे उद्घाटन करण्यात आले.",
        sortOrder: 4,
        isActive: true,
      },
      {
        id: "gallery-5",
        titleEn: "Head Office Central Conference Meeting",
        titleMr: "मुख्य कार्यालय केंद्रीय आढावा बैठक",
        category: "inauguration",
        imageUrl: "/images/photo-10.jpeg",
        descriptionEn: "Review meeting of branch managers discussing core digital banking installations.",
        descriptionMr: "मुख्य डिजिटल बँकिंग सेवांच्या स्थापनेवर चर्चा करण्यासाठी शाखा व्यवस्थापकांची आढावा बैठक.",
        sortOrder: 5,
        isActive: true,
      },
      {
        id: "gallery-6",
        titleEn: "Technology Summit & Digital Launch",
        titleMr: "तंत्रज्ञान परिषद व डिजिटल सेवा प्रारंभ",
        category: "agm",
        imageUrl: "/images/photo-2.jpeg",
        descriptionEn: "Rollout event introducing mobile application UPI integration for local cooperative businesses.",
        descriptionMr: "स्थानिक सहकारी व्यवसायांसाठी मोबाईल ॲप्लिकेशन युपीआय (UPI) एकत्रीकरण सुरू करण्याचा कार्यक्रम.",
        sortOrder: 6,
        isActive: true,
      },
      {
        id: "gallery-7",
        titleEn: "Community Cycling & Awareness Event",
        titleMr: "सायकल जनजागृती व सामाजिक सहभाग कार्यक्रम",
        category: "social",
        imageUrl: "/images/photo-7.jpeg",
        descriptionEn: "Cycling awareness rally and community participation event organized by the society members.",
        descriptionMr: "संस्थेच्या सदस्यांद्वारे आयोजित सायकल जनजागृती रॅली आणि सामाजिक सहभाग कार्यक्रम.",
        sortOrder: 7,
        isActive: true,
      },
      {
        id: "gallery-8",
        titleEn: "Society Group Celebration & Meet",
        titleMr: "सदस्य मेळावा व समाज स्नेहसंमेलन",
        category: "social",
        imageUrl: "/images/photo-8.jpeg",
        descriptionEn: "Group gathering and celebration with members, directors, and community participants.",
        descriptionMr: "सदस्य, संचालक आणि सामाजिक सहभाग घेणाऱ्यांसोबत एकत्रित सोहळा आणि स्नेहसंमेलन.",
        sortOrder: 8,
        isActive: true,
      },
      {
        id: "gallery-9",
        titleEn: "Community Felicitation Ceremony",
        titleMr: "समाज गौरव व सत्कार समारंभ",
        category: "social",
        imageUrl: "/images/photo-6.jpeg",
        descriptionEn: "Honouring members and dignitaries during a cooperative society felicitation program.",
        descriptionMr: "सहकारी संस्था सत्कार समारंभादरम्यान सदस्य आणि मान्यवरांचा गौरव.",
        sortOrder: 9,
        isActive: true,
      },
      {
        id: "gallery-10",
        titleEn: "Annual Conference & Public Address",
        titleMr: "वार्षिक परिषद व मार्गदर्शन कार्यक्रम",
        category: "agm",
        imageUrl: "/images/photo-5.jpeg",
        descriptionEn: "Leadership addressing members during the annual cooperative society conference.",
        descriptionMr: "वार्षिक सहकारी संस्था परिषदेदरम्यान सदस्यांना मार्गदर्शन करताना नेतृत्व.",
        sortOrder: 10,
        isActive: true,
      },
    ];

    for (const item of defaultGalleryItems) {
      await prisma.galleryMedia.upsert({
        where: { id: item.id },
        update: item,
        create: item,
      });
    }
    console.log("Gallery media seeded successfully.");

    for (const b of branches) {
      await prisma.branch.upsert({
        where: { id: b.id },
        update: b,
        create: b,
      });
    }

    console.log("Branches seeded successfully.");
}

main()
    .catch(console.error)
    .finally(async () => {
        await prisma.$disconnect();
    });